ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      clear
      pip install poetry
      poetry install
      gp sync-done python
    command: poetry run django-admin runserver --settings=tests.settings.dev --pythonpath=.
    name: Runserver

  - init: |
      clear
      nvm install
      npm install
    command: npm run start
    name: Node
    openMode: split-right

  - init: |
      clear
      gp sync-await python
    command: poetry run ./runtests.py
    name: Tests
    openMode: split-right

  - init: |
      clear
    command: |
      echo "There are 3 terminals ready to use"
      echo "1. Runserver: is running the django dev-server on http://127.0.0.1:8000"
      echo "2. Tests: will run the tests once and wait for 'poetry run ./runtests.py' to run the tests again"
      echo "3. Node: will run 'npm run start' and watch files for changes"
      echo "4. Bash: is this terminal and can be use to run other adhoc commands"
      echo "Try out the render_patterns command: 'poetry run django-admin render_patterns --settings=tests.settings.dev --pythonpath=.' and look in the 'dpl-rendered-patterns' folder"
    openMode: tab-after
