ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      clear
      pip install poetry
      poetry install
      gp sync-done python
    command: poetry run django-admin runserver --settings=tests.settings.dev --pythonpath=.
    name: Runserver

  - init: |
      clear
      nvm install
      npm install
    command: npm run build
    name: Node
    openMode: split-right

  - init: |
      clear
      echo "Waiting for python..."
      gp sync-await python
    command: |
      poetry run ./runtests.py
      poetry run django-admin render_patterns --settings=tests.settings.dev --pythonpath=.
    name: Tests
    openMode: split-right
