version: ~> 1.0
os: linux
dist: bionic
language: python
cache:
  pip: true
  directories:
    - .tox
    - node_modules
jobs:
  include:
    - env: PYVER=py36
      python: 3.6
    - env: PYVER=py37
      python: 3.7
    - env: PYVER=py38
      python: 3.8
    - language: node_js
      install:
        - npm install --no-optional --no-audit --progress=false
      script:
        - npm run build
    - python: 3.8
      install:
        - pip install poetry
        - poetry install
      script:
        - cp README.md docs/README.md
        - poetry run mkdocs build
install:
  - pip install poetry tox
script:
  - tox -e lint
  - tox -e $(tox -l | grep ${PYVER} | xargs echo | sed 's/ /,/g')
branches:
  except:
    - gh-pages
notifications:
  email: false
