site_name: django-pattern-library
repo_url: https://github.com/torchbox/django-pattern-library
site_url:
edit_uri: edit/master/docs/

repo_name: django-pattern-library
dev_addr: 0.0.0.0:8001
theme:
  name: material
  font: false
  palette:
    primary: indigo
  logo: images/logo.svg
  favicon: images/favicon.png
markdown_extensions:
  - codehilite
  - admonition
  - sane_lists
  - toc:
      permalink: true
  # pymdown-extensions meant to bring the Markdown implementation closer to GFM.
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  # Ideally these should be in a "Guides" section, however it’s not currently possible to
  # display those sections expanded by default.
  # See https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/.
  # Choose the order carefully from fundamental topics to advanced ones.
  - 'Template context': 'guides/defining-template-context.md'
  - 'Overriding tags': 'guides/overriding-template-tags.md'
  - 'Customizing rendering': 'guides/customizing-template-rendering.md'
  - 'Workflows that work': 'guides/workflows-that-work.md'
  - 'Reuse across projects': 'guides/reuse-across-projects.md'
  - 'Recipes':
    - 'Inclusion tags': 'recipes/inclusion-tags.md'
    - 'Looping for tags': 'recipes/looping-for-tags.md'
    - 'Image include': 'recipes/image-include.md'
    - 'Image lazyload': 'recipes/image-lazyload.md'
    - 'Multiple variants': 'recipes/multiple-variants.md'
  - 'Reference':
    - 'API and settings': 'reference/api.md'
    - 'Concepts': 'reference/concepts.md'
    - 'Known issues': 'reference/known-issues.md'
    - 'Related projects': 'reference/related-projects.md'
