site_name: django-pattern-library
repo_url: https://github.com/torchbox/django-pattern-library
site_url:
edit_uri: edit/master/docs/

repo_name: django-pattern-library
dev_addr: 0.0.0.0:8001
theme:
  name: material
  font: false
  palette:
    primary: indigo
  logo: images/logo.svg
  favicon: images/favicon.png
markdown_extensions:
  - codehilite
  - admonition
  - sane_lists
  - toc:
      permalink: true
  # pymdown-extensions meant to bring the Markdown implementation closer to GFM.
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  # Ideally these should be in a "Guides" section, however it’s not currently possible to
  # display those sections expanded by default.
  # See https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/.
  # Choose the order carefully from fundamental topics to advanced ones.
  - 'Defining template context': 'guides/defining-template-context.md'
  - 'Overriding template tags': 'guides/overriding-template-tags.md'
  - 'Customizing template rendering': 'guides/customizing-template-rendering.md'
  - 'Reference':
    - 'Concepts': 'reference/concepts.md'
    - 'Examples': 'reference/examples.md'
    - 'Related projects': 'reference/related-projects.md'
