site_name: django-pattern-library
repo_url: https://github.com/torchbox/django-pattern-library
site_url:
edit_uri: edit/main/docs/

repo_name: django-pattern-library
dev_addr: localhost:8001
theme:
  name: material
  font: false
  palette:
    primary: indigo
  logo: images/logo.svg
  favicon: images/favicon.png
markdown_extensions:
  - codehilite
  - admonition
  - sane_lists
  - toc:
      permalink: true
  # pymdown-extensions meant to bring the Markdown implementation closer to GFM.
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date
  - redirects:
      redirect_maps:
        'reference/related-projects.md': 'community/related-projects.md'
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  # The most important guides are shown in the top-level navigation.
  - 'Template context': 'guides/defining-template-context.md'
  - 'Overriding tags': 'guides/overriding-template-tags.md'
  - 'Usage tips': 'guides/usage-tips.md'
  - 'Guides':
    - 'Customizing rendering': 'guides/customizing-template-rendering.md'
    - 'Multiple variants': 'guides/multiple-variants.md'
    - 'Automated tests': 'guides/automated-tests.md'
    - 'Static site export': 'guides/static-site-export.md'
    - 'Reuse across projects': 'guides/reuse-across-projects.md'
  - 'Recipes':
    - 'Forms and fields': 'recipes/forms-and-fields.md'
    - 'Image include': 'recipes/image-include.md'
    - 'Image lazyload': 'recipes/image-lazyload.md'
    - 'Inclusion tags': 'recipes/inclusion-tags.md'
    - 'Looping for tags': 'recipes/looping-for-tags.md'
    - 'Pagination': 'recipes/pagination.md'
    - 'API rendering': 'recipes/api-rendering.md'
  - 'Reference':
    - 'API and settings': 'reference/api.md'
    - 'Concepts': 'reference/concepts.md'
    - 'Known issues': 'reference/known-issues.md'
  - 'Community':
    - 'Support': 'community/support.md'
    - 'Related projects': 'community/related-projects.md'
    - 'Code of conduct': 'community/code-of-conduct.md'
    - 'Security policy': 'community/security-policy.md'
  - 'Online demo': '/django-pattern-library/demo/'
